server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: "/meetingfilm/" #统一前缀
  routes: ## 路由规则
    meetingfilm-user:
      path: /userapi/**  # 匹配规则
      serviceId : user-service # application.name --> 服务名称 service-id
      retryable: true  # 是否允许重试, 饿汉模式
    meetingfilm-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    meetingfilm-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    meetingfilm-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true
  sensitive-headers: # Zuul默认会过滤一些头信息, 需要进行过滤设置, 如果为空表示所有header都可以通过
#  ignored-headers: #和sensitive-headers功能相反, 表示经过配置的才是可以放行的, 没有配置不能放行

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000